# Generated by Django 4.2.20 on 2025-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default="7E2FCF34CB",
                editable=False,
                max_length=32,
                unique=True,
                verbose_name="Order Number",
            ),
        ),
    ]
