# Generated by Django 4.2.20 on 2025-05-01 18:06

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/featured/",
                verbose_name="Featured Image",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=products.models.product_image_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Accessibility text for screen readers",
                        max_length=255,
                        verbose_name="Alternative Text",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order to display images",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., Size, Color, Material",
                        max_length=100,
                        verbose_name="Variation Name",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="E.g., Large, Red, Cotton",
                        max_length=100,
                        verbose_name="Variation Value",
                    ),
                ),
                (
                    "sku_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Will be appended to product SKU",
                        max_length=20,
                        verbose_name="SKU Suffix",
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount to add/subtract from base price",
                        max_digits=10,
                        verbose_name="Price Adjustment",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock Quantity"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.models.product_image_path,
                        verbose_name="Variation Image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variation",
                "verbose_name_plural": "Product Variations",
                "ordering": ["product", "name", "value"],
                "unique_together": {("product", "name", "value")},
            },
        ),
    ]
