# Generated by Django 4.2.20 on 2025-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(blank=True, verbose_name="Shipping Address"),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="Billing Address"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Joined"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("new", "New"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("former", "Former"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="Customer Status",
                    ),
                ),
                (
                    "accepts_marketing",
                    models.BooleanField(
                        default=False, verbose_name="Accepts Marketing"
                    ),
                ),
                (
                    "preferred_communication",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("sms", "SMS"),
                        ],
                        default="email",
                        max_length=10,
                        verbose_name="Preferred Communication",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
            },
        ),
    ]
